### PR TITLE
Done Task1 And Task2

### PR DESCRIPTION
**Pull request by LavishGulati**

### CODE REVIEW

**Comment by deepakgouda** [comment]
You do not need to create a null array/list every time and append values. You can simply write 
``` x = np.random.random(500)```

**Comment by deepakgouda** [comment]
There are some conflicts. Do a git pull and add your files. :-)

**Comment by LavishGulati** [comment]
But np.random.random() creates random values between 0 and 1 only. It would be better to take random values in a wider range.

**Comment by LavishGulati** [comment]
Conflicts resolved!

**Comment by deepakgouda** [comment]
No, I meant to say that, in Task1.ipynb, instead of
```
A = [] 
A.append(np.random.random(500))
```
you can write a single line
``` A = np.random.random(500) ```

**Pull request merged**
